# Generated by Django 2.2.6 on 2019-10-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerecord',
            name='operator_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='VariableRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField()),
                ('machine_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_records', to='records.MachineRecord')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.Variable')),
            ],
        ),
    ]
