# Generated by Django 2.2.6 on 2019-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191026_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerecord',
            name='stop_timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
